### ISSUE TITLE
IC2 Support

### ISSUE THREAD

**Issue by IcaroKaue** [MuXiu1997/GTNH-translation-compare#7]
Though IC2 has its own translations built in, sometimes we need to change terms so they are consistent with the rest of the pack. IC2 seems to store its lang file in a different way than other mods. Instead of storing it in "industrialcraft-2-2.2.828a-experimental.jar\assets\ic2\lang\aa_BB.lang", it stores it in "industrialcraft-2-2.2.828a-experimental.jar\ic2\lang\aa_BB.lang". 
Though a lang file is present in "industrialcraft-2-2.2.828a-experimental.jar\assets\minecraft\en_IC.lang" it appears to not have machine or material names.

**Comment by IcaroKaue** [comment]
Update: adding a modified en_US.properties to txloader\IC2 and txloader\IC2\ic2\lang does not seem to work. Maybe modifying the .jar directly is needed.

**Comment by MuXiu1997** [comment]
This seems to be a known issue that no one has attempted to solve yet. This is not a part that this repository is responsible for
